_time = 0;
_frame_skip = 0;
_frame_skipped = 0;
global.blur_strength = 0;
global.blur_amount = 0;
global.classic_ui = 0;
global.Panel = battle_menu_fight_knife;
global.kr = 1;
global.surface_gui = surface_create(640, 480);