depth = DEPTH_BATTLE.SOUL;
image_speed = 0;
image_blend = c_white;
al = 0.7 * !global.classic_ui;
moveable = 1;
if (!global.classic_ui) Anim_Create(id, "al", ANIM_TWEEN.CUBIC, ANIM_EASE.OUT, al, -al, 35);
s = 0;
ss = 0;
index = 1;
follow_board = false;
_inv = 0;
global.moving = 0;