event_inherited();
moveable = 1;
dir = 270;
move = 0;
impact = 0;
on_block = 0;
on_platform = 0;
on_board = 0;
jump_state = 0;
inst_plat = noone;
image_blend=c_blue;
gravity_jump = 0.15;
gravity_fall = 0.15;
jump_speed = 4.8;
max_speed = 20;
moving = 0;
